### PR TITLE
Prevent crash in GotoFirstNonBlankOfLine

### LINKED ISSUE #2050: [vi-mode] GotoFirstNonBlankOfLine crashes PSRL when buffer is empty
## Environment

```none
PS version: 7.2.0-daily.20201215
PSReadline version: 2.1.0
os: 10.0.18362.1130 (WinBuild.160101.0800)
PS file version: 7.2.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

## Exception report

Last 24 Keys
```
 S e t - P S R e a d L i n e O p t i o n RightArrow Enter Escape _
```

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.IsVisibleBlank(Int32 newCurrent)
   at Microsoft.PowerShell.PSConsoleReadLine.GetFirstNonBlankOfLogicalLinePos(Int32 current)
   at Microsoft.PowerShell.PSConsoleReadLine.GotoFirstNonBlankOfLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Run PSRL:

> Set-PSReadLineOption -EditMode Vi

Then type the following sequence: <kbd>Esc</kbd>, <kbd>_</kdb>

## Expected behavior

Nothing should happen. Possibly, key may ding.

## Actual behavior

PSRL crashes.

### PR DESCRIPTION
**Pull request by springcomp**
# PR Summary

Fixes #2050.

The method `GetBeginningOfLinePos` is updated to remove call to `LineIsMultiline` that do not check the buffer input and attempts to access the underlying `_buffer`.  Additionally, the method `GetFirstNonBlankOfLogicalLinePos` protects access to the `_buffer` member.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [x] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/PowerShell/PSReadLine/pull/2051)

### CODE REVIEW

File: PSReadLine/Position.cs [hunk 1]
```diff
@@ -11,28 +11,17 @@ public partial class PSConsoleReadLine
...
-
-                newCurrent = i;
-            }
-            else
-            {
-                newCurrent = 0;
             }
 
-            return newCurrent;
+            return i;
```
Comment (daxian-dbw) [inline PSReadLine/Position.cs:24]: The change to `GetBeginningOfLinePos` is duplicate in #2047, you may remove from this PR.

**Review by daxian-dbw — COMMENTED** [review]
LGTM with 1 comment.

File: PSReadLine/Position.cs (hunk 1 above)
Comment (springcomp) [reply PSReadLine/Position.cs:24]: Exactly, just wanted to give you flexibility to accept either PR in the order that you wanted.

**Review by daxian-dbw — APPROVED** [review]
