### PR TITLE
Fix 2 menu completion issues that happen when we need to scroll screen buffer

### LINKED ISSUE #2928: Tab autocomplete in a Cmdlet param context
### Prerequisites

- [X] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.0-beta3
PowerShell: 7.1.5
OS: Microsoft Windows 10.0.22483
BufferWidth: 133
BufferHeight: 30

Last 200 Keys

 Spacebar Enter
 $ i Tab n s Enter
 Spacebar - r e p l Tab Spacebar " " LeftArrow C : \ \ U s e r s \ \ m a v a d Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow RightArrow RightArrow \ \ Ctrl+RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow \ \ Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow , " " LeftArrow $ e n v : H O M E Tab RightArrow Enter
 Ctrl+LeftArrow Ctrl+LeftArrow ` Ctrl+RightArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+RightArrow LeftArrow Enter
 UpArrow Spacebar | Spacebar s e t - c l i Tab Enter
 UpArrow UpArrow UpArrow ) Home Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow ( End Spacebar - r e p Tab Spacebar Spacebar " C : \ \ \ \ U s e r s \ \ \ \ m a v a d " , " ` $ e n v : H O M E P A T H " Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Shift+Ctrl+RightArrow Shift+Ctrl+RightArrow Shift+Ctrl+RightArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Delete $ e n v : H O M E Tab RightArrow Enter
 Ctrl+LeftArrow Ctrl+LeftArrow Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Backspace Ctrl+RightArrow Ctrl+RightArrow LeftArrow LeftArrow LeftArrow Delete Spacebar LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow Spacebar [ ] LeftArrow r e g Tab

### Exception
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 30.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

I attempted to tab here.
Tab attempted at this position of the line

### Environment data

```console
PS Version: 7.1.5
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta3
PSReadLine EditMode: Windows
OS: 10.0.22483.1000 (WinBuild.160101.0800)
BufferWidth: 133
BufferHeight: 30
```

### Steps to reproduce

To get the error in the first place, I recalled the following into `Pwsh` without pressing `enter` (by pressing `up` arrow to recall last command):

```pwsh
$instMods = (Get-InstalledModule  | ConvertTo-Html | pandoc.exe --from=html-auto_identifiers-native_spans-native_divs --to=gfm-gfm_auto_identifiers) -replace  [reg] $env:HOMEPATH ,"`$env:HOMEPATH"
```

Nav back to the position at `reg` inside `[reg]  $env` and press `tab`.

### Expected behavior

Autocomplete `regex` assembly inside square brackets.

### Actual behavior

`System.ArgumentOutOfRangeException`

### LINKED ISSUE #2948: Menu completion doesn't work properly when scrolling happens
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
No exception report.
```

### Screenshot

Animation

### Environment data

```console
PS Version: 7.1.3
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta4
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 133
BufferHeight: 30
```

### Steps to reproduce

1. Press <kbd>Enter</kbd> a number of times until the prompt is at the last line of the terminal window
2. Copy and paste the following command to the terminal: ``$instMods = (Get-InstalledModule | ConvertTo-Html | pandoc12.exe --from=html-auto_identifiers-native_spans-native_divs --to=gfm-gfm_auto_identifiers) -replace [reg] $env:HOMEPATH ,"`$env:HOMEPATH"``
3. Move cursor to the closing bracket `]` of the `[reg]`.
4. Press <kbd>Ctrl+Space</kbd> to trigger the menu completion
5. Move the selection to `RegisterPSSessionConfigurationCommand`

Here is the GIF for reproducing this:

Animation

### Expected behavior

The menu completion should work correctly when moving selection around, even though necessary screen scrolling is needed.

### Actual behavior

As is shown, the menu completion rendering is broken in this case, where screen buffer scrolling was needed when initially rendering the menu.

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #2928
Fix #2948

The details of the issues and root cause can be found at https://github.com/PowerShell/PSReadLine/issues/2928#issuecomment-961295959 and https://github.com/PowerShell/PSReadLine/issues/2948#issuecomment-961313213

Major changes in this PR:
1. Handle moving the cursor to the start-drawing position appropriately, taking screen buffer scrolling in consideration.
2. Move duplicate code into the function `MoveCursorToStartDrawingPosition` and used it for both menu completion and dynamic help.
3. Initialize `PreviousTop` correctly before `Top` is changed, and get rid of `bufferEndPoint.Y` because we should compare `Top` with `PreviousTop` to determine if menu moved.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
      - **Cannot add tests because we cannot mimic buffer scrolling with the testing console, but I manually validated the fix**
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/2949)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@andschwa Can you please do a sanity check for me? Thanks!

File: PSReadLine/Completion.cs [hunk 1]
```diff
@@ -879,7 +870,6 @@ private void MenuCompleteImpl(Menu menu, CommandCompletion completions)
 
                         if (topAdjustment != 0)
                         {
-                            menu.Top += topAdjustment;
```
Comment (andyleejordan) [inline PSReadLine/Completion.cs:882]: This PR makes sense to me (given your investigations and the rest of the changes here) except that I can't account for why `menu.Top` no longer needs to be adjusted.

**Review by andyleejordan — APPROVED** [review]

File: PSReadLine/Completion.cs (hunk 1 above)
Comment (daxian-dbw) [reply PSReadLine/Completion.cs:882]: Good question! `Top` will be adjusted properly within `menu.DrawMenu`. Adjusting it here will make the `PreviousTop` incorrect within `menu.DrawMenu`.

Comment (andyleejordan) [reply PSReadLine/Completion.cs:882]: Thanks for the follow-up!
