### PR TITLE
Fix correct way to get substring based on buffercells when encountering CJK chars

### LINKED ISSUE #847: 'GetMenuItem' throw ArgumentOutOfRangeException for CKJ completion items
問題が発生しました。このバグを以下の詳細と共に報告してください。
GitHub で報告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
直前 200 個のキー:
 s t o p - p r o Ctrl+Space Space - n a e m Space Backspace Backspace Backspace m e Space e x c e l Enter
 $ a Backspace A p p Space = Space Space n e w - o b j e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace $ A p p Space = Space N e w - o b j e c t Ctrl+Space Ctrl+Space Space - c o m Ctrl+Space Space E x c e l . A p p l i c a t i o n Enter
 Backspace Backspace Backspace Backspace $ A p p . V i s i b l e Space = Space $ F a l s e Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace T r u e Enter
 $ A p p . W o r k b o o k s . O p e n 　 Space Backspace Space Space = Space Backspace Backspace Backspace Backspace ( " D : \ LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow RightArrow Ctrl+Space u Enter
 Ctrl+Space RightArrow Enter
 Ctrl+Space

例外:
System.ArgumentOutOfRangeException: インデックスおよび長さは文字列内の場所を参照しなければなりません。
パラメーター名:length
   場所 System.String.Substring(Int32 startIndex, Int32 length)
   場所 Microsoft.PowerShell.PSConsoleReadLine.GetMenuItem(String item, Int32 columnWidth)
   場所 Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   場所 Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   場所 Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   場所 Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Code was correctly calculating the number of buffer cells for CJK chars, but then used substring() to get a substring which failed as the number of cells is > number of chars.  Fix is to have a SubstringByCells() method that understands how to return substring based on cells.  Also using unicode ellipsis char instead of `...` to save screen space.

Tried to add a unittest, but couldn't get the CJK char to work with KeyboardLayout.

Fix https://github.com/PowerShell/PSReadLine/issues/847

### CODE REVIEW

File: PSReadLine/Render.cs [hunk 1]
```diff
@@ -51,6 +51,7 @@ class RenderData
             public RenderedLineData[] lines;
         }
 
+        private const char ELLIPSIS = '\u2026';
```
Comment (lzybkr) [inline PSReadLine/Render.cs]: What about terminals that don't support Unicode?

File: PSReadLine/Render.cs [hunk 2]
```diff
@@ -875,6 +876,26 @@ private static int LengthInBufferCells(char c)
             return 1 + (isWide ? 1 : 0);
         }
 
+        private static string SubstringByCells(string text, int countOfCells)
+        {
+            int length = 0;
+            int index = 0;
+            string substring = string.Empty;
```
Comment (lzybkr) [inline PSReadLine/Render.cs]: This variable seems unnecessary.

Comment (SteveL-MSFT) [reply PSReadLine/Render.cs]: Yes, I think I had something different in mind initially.

File: PSReadLine/Render.cs (hunk 1 above)
Comment (SteveL-MSFT) [reply PSReadLine/Render.cs]: I haven't seen a modern terminal that doesn't support it including Win7.

Comment (lzybkr) [reply PSReadLine/Render.cs]: I booted a bare metal Arch iso and it seems that does not support Unicode:

image

Comment (SteveL-MSFT) [reply PSReadLine/Render.cs]: Ok, I'll change it back.

**Review by lzybkr — APPROVED** [review]

**Review by daxian-dbw — APPROVED** [review]
