### PR TITLE
Fix `ViModeIndicator = Cursor` for Windows Terminal

### LINKED ISSUE #1233: ViModeIndicator = Cursor does not work in Windows Terminal
Using `Set-PSReadLineOption -EditMode vi -viModeIndicator Cursor` on Windows Terminal does not display any differences based on the mode you are in. It's likely due to Windows Terminal accepting the [DECSCUSR](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) escape sequence as opposed to whatever Windows Console supported.

### LINKED ISSUE #3334: -ViModeIndicator "Cursor" option not applying correctly on Windows Terminal
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [x] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.2.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.5
PSReadLine EditMode: Vi
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

- With Vi mode activated, use `Set-PSReadLineOption -ViModeIndicator "Cursor"`
- Since the console starts on Insert mode, press scape to change to Normal.

### Expected behavior

Like using "pure" powershell: cursor starts as "classic" (Insert mode) and then goes to "block" (Normal mode).

### Actual behavior

Cursor stays the same, though it goes left one position.

Note that I've a vertical bar as the WT cursor, but I changed it to "classic" to see what happens and it doesn't work either.

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary
Fix #3334 
Fix #1233

Fix `ViModeIndicator = Cursor` for Windows Terminal by writing out escape sequences that configure cursor shape.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/3374)

### CODE REVIEW

File: PSReadLine/ConsoleLib.cs [hunk 1]
```diff
@@ -45,9 +45,15 @@ public virtual int CursorSize
...
                     _unixCursorSize = value;
-                    // Solid blinking block or blinking vertical bar
-                    Write(value > 50 ? "\x1b[2 q" : "\x1b[5 q");
                 }
+
+                // See the cursor ANSI codes at https://www.real-world-systems.com/docs/ANSIcode.html, searching for 'blinking block'.
+                // We write out the ANSI escape sequence even if we are on Windows, where the 'Console.CursorSize' API is supported by .NET.
+                // This is because this API works fine in console host, but not in Windows Terminal. The escape sequence will configure the
+                // cursor as expected in Windows Terminal, while in console host, the escape sequence works after it's written out, but then
+                // will be overwritten by 'CursorSize' when the user continues typing.
```
Comment (andyleejordan) [inline PSReadLine/ConsoleLib.cs:54]: Does this mean there's a bit of a race condition where it can look unexpectedly different before the user continues typing?

**Review by andyleejordan — APPROVED** [review]

File: PSReadLine/ConsoleLib.cs (hunk 1 above)
Comment (daxian-dbw) [reply PSReadLine/ConsoleLib.cs:54]: There could be. The blinking underscore shape from Ansi code is thinner that "Console.CursorSize = 25" in console host, but not different too much. In Windows Terminal, there is no race condition, since we can change the cursor shape only through the Ansi sequences.

**Comment by daxian-dbw** [comment]
Thanks @andschwa for the review!
