### PR TITLE
Fix a null-ref exception in `DynamicHelpImpl`

### LINKED ISSUE #2283: Dynamic Help - NullReferenceException in Powershell 7.2.0-preview.3 and Windows Powershell 5.1.19041.610
## Environment

```
PS version: 7.2.0-preview.3
PSReadline version: 2.2.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.2.0.0
HostName: ConsoleHost
BufferWidth: 157
BufferHeight: 9999
```

```
PS version: 5.1.19041.610
PSReadline version: 2.2.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 155
BufferHeight: 9999
```

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-preview.3
OS: Microsoft Windows 10.0.19042
BufferWidth: 190
BufferHeight: 55

Last 1 Keys
```
 F1
```

### Exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.DynamicHelpImpl(Boolean isFullHelp)
   at Microsoft.PowerShell.PSConsoleReadLine.ShowCommandHelp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Open a fresh Powershell console and press `F1`.
Reproduces with no profile loaded (`pwsh -noprofile`) and no modules other than the latest PSReadLine

```powershell
PS C:\Users\carloc> gmo

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.0      beta2      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSRe…
```

**Note**: no error with PowerShell 7.1.2

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #2283
Fix a null-ref exception in `DynamicHelpImpl`.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [x] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/2292)

### CODE REVIEW

File: test/DynamicHelpTest.cs [hunk 1]
```diff
@@ -97,6 +97,13 @@ private static PSObject GetParameterHelpObject(string description)
             return paramHelp;
         }
 
+        [SkippableFact]
+        public void DynHelp_GetFullHelp_OnEmptyLine()
+        {
+            TestSetup(KeyMode.Cmd);
+            Test("", Keys(_.F1, _.Enter));
```
Comment (adityapatwardhan) [inline test/DynamicHelpTest.cs:104]: Should we verify that the console in unchanged?

**Review by adityapatwardhan — APPROVED** [review]

File: test/DynamicHelpTest.cs (hunk 1 above)
Comment (daxian-dbw) [reply test/DynamicHelpTest.cs:104]: I think this should be fine.
