### PR TITLE
Fix the null-reference exception when running `Debug-Job` on a thread job

### LINKED ISSUE #3954: Using `Debug-Job` to debug a background / thread job causes a crash
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
VERBOSE: Waiting for job to be in the 'Running' state...
VERBOSE: Starting debugging...
At line:2 char:10
+   while ($true) { Start-Sleep -Milliseconds 100 }
+          ~~~~~
[DBG]: [Job12]: PS /Users/jdoe>>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.5.0-preview.1
OS: Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
BufferWidth: 180
BufferHeight: 60

Last 33 Keys:

 p g Enter
 p g Enter
 p g Enter
 p g Enter
 g j b Enter
 g m o Enter
 p g Enter
 p g Enter
 c l r Enter
 p g Enter


### Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.UpdatePredictionClient(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.5.0-preview.1
PS HostName: ConsoleHost
PSReadLine Version: 2.3.4
PSReadLine EditMode: Emacs
OS: Darwin SomeMachine.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
BufferWidth: 180
BufferHeight: 60
```

### Steps to reproduce

```powershell
$jb = Start-ThreadJob {
  while ($true) { Start-Sleep -Milliseconds 100 }
}

try {

  Write-Verbose -Verbose 'Waiting for job to be in the ''Running'' state...'
  while ($jb.State -notin  'Running') { Start-Sleep -Milliseconds 100 }

  Write-Verbose -Verbose 'Starting debugging...'
  $jb | Debug-Job

}
finally {
  if ($jb) { $jb | Remove-Job -Force }
}
```

### Expected behavior

The debugger should be entered and behave normally.

### Actual behavior

`PSReadLine` crashes with the output above.

### PR DESCRIPTION
**Pull request by daxian-dbw**
### PR Summary

Fix #3954 

The `$Host.Runspace` is null when `PSConsoleHostReadLine` is invoked while debugging a thread job.
This is because a thread job uses the default host, which always has value `null` for `$Host.Runspace`.
We set the current path to be `null` when either `runspace` or `engineIntrinsics` is null.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/PowerShell/PSReadLine/pull/3957)

### CODE REVIEW

File: PSReadLine/Prediction.cs [hunk 1]
```diff
@@ -50,7 +50,9 @@ private static void UpdatePredictionClient(Runspace runspace, EngineIntrinsics e
             if (s_pCurrentLocation is not null)
             {
                 // Set the current location if it's a local Runspace. Otherwise, set it to null.
-                object path = runspace.RunspaceIsRemote ? null : engineIntrinsics.SessionState.Path.CurrentLocation;
+                object path = runspace is null || runspace.RunspaceIsRemote
+                    ? null
+                    : engineIntrinsics?.SessionState.Path.CurrentLocation;
```
Comment (anamnavi) [inline PSReadLine/Prediction.cs:55]: What happens if `engineIntrinsics` is null (since the type is nullable)? The path would become null then too..is that expected or would the caller method always ensure it's not null?

**Review by anamnavi — APPROVED** [review]

File: PSReadLine/Prediction.cs (hunk 1 above)
Comment (anamnavi) [reply PSReadLine/Prediction.cs:55]: oops, I see this is answered in the PR description.
