### PR TITLE
Check error condition in VkKeyScan

### LINKED ISSUE #787: TypeInitializationException again
I'm getting exactly the same error as #614 but with a local build from the latest master of PSReadLine that I built using the ENG keyboard layout, and then use the ITA layout to test.

Environment data
----------------

```
PS version: 5.1.17763.1
PSReadline version: 2.0.0-beta3
os: 10.0.17763.102 (WinBuild.160101.0800)
PS file version: 10.0.17763.102 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------
```
❯ Get-PSReadLineOption
Get-PSReadLineOption : L'inizializzatore di tipo di 'Microsoft.PowerShell.PSConsoleReadLine' ha generato un'eccezione.
In riga:1 car:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
    + FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```

### PR DESCRIPTION
**Pull request by lzybkr**
VkKeyScan returns -1 when there is no key mapping for the given
character.

This possiblity was not considered, resulting in an attempt to add
duplicate (but invalid) keys to the CtrlKeyToKeyMap.

Fixes #787

### CODE REVIEW

File: PSReadLine/Keys.cs [hunk 1]
```diff
@@ -66,8 +66,11 @@ static ConsoleKeyInfo CtrlAlt(char c)
             if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
             {
                 var keyWithMods = WindowsKeyScan(c);
-                shift = (keyWithMods.Modifiers & ConsoleModifiers.Shift) != 0;
-                key = keyWithMods.Key;
+                if (keyWithMods.HasValue)
+                {
+                    shift = (keyWithMods.Value.Modifiers & ConsoleModifiers.Shift) != 0;
```
Comment (SteveL-MSFT) [inline PSReadLine/Keys.cs:71]: Why not use HasFlag()?

**Review by SteveL-MSFT — APPROVED** [review]
