### PR TITLE
Avoid rendering dead keys (2nd attempt)

### LINKED ISSUE #914: Beta 4: problems with dead keys and custom keyboard layout (Neo2)
I use a custom keyboard layout called Neo2 offering multiple layers using modifier keys, e.g. `<CAPS-LOCK>+<k>` results in `)`
Since installing beta4 of PSReadline, every time I press `<CAPS-LOCK>` a @ character is added to my input, So instead of
`git commit -am "message"`
 I end up "typing"
`git commit @-am @"message@"`

Environment data
----------------
PS version: 5.1.17763.316 / same for 6.2
PSReadline version: 2.0.0-beta4
os: 10.0.17763.470 (WinBuild.160101.0800)
PS file version: 10.0.17763.470 (WinBuild.160101.0800)
vi **or** standard edit mode.

Steps to reproduce or exception report
--------------------------------------
Install the Neo2 driver: https://github.com/neo-layout/neo-layout/blob/master/windows/Neo2.0_setup.exe
And add the "German (Neo 2.0)" keyboard layout to your input settings, open powershell and hit \<caps-lock\>

### PR DESCRIPTION
**Pull request by daxian-dbw**
Use a heuristic check to determine if a key pressing is a dead key. Fix #914 

The Win32 API `ToUnicode` doesn't work well with non-natively-supported keyboard layouts, such as the Neo keyboard layout. `ToUnicode` maps Neo dead keys to unicode characters incorrectly and results in PSReadLine rendering the dead keys.

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@Snaptags this fix seems to be working fine with Neo. Can you please give it another try?

**Comment by Snaptags** [comment]
Dead key handling is working perfectly! Thank you for this great fix.

**Comment by daxian-dbw** [comment]
Thanks @Snaptags for trying it out.
@lzybkr can you please review this fix? Thanks!

File: PSReadLine/Keys.cs [hunk 1]
```diff
@@ -221,22 +222,36 @@ void AppendPart(string str)
...
                 // If this fails, we rely on some hard coded control characters below.
                 if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                 {
-                    var keySansControl = new ConsoleKeyInfo(key.KeyChar, key.Key, isShift, isAlt, control: false);
-                    TryGetCharFromConsoleKey(keySansControl, ref c, ref isDeadKey);
+                    // A heuristic to check for dead keys --
+                    //   We got an 'OemXXX' ConsoleKey, '\0' key char, and no 'Ctrl' modifier. It's very likely generated by a dead key.
+                    //   We check for 'Ctrl' modifier because it's easy to generate '\0' KeyChar and 'OemXXX' by combinding 'Ctrl' with
+                    //   another special key, such as 'Ctrl+?' and 'Ctrl+;'.
+                    isDeadKey = (c == '\0') && (consoleKey >= ConsoleKey.Oem1 && consoleKey <= ConsoleKey.Oem102) && !isCtrl;
```
Comment (lzybkr) [inline PSReadLine/Keys.cs:243]: There is a large gap of invalid values in that range - maybe you should use a switch?
You also miss `OemClear` in that range.

**Review by lzybkr — APPROVED** [review]

File: PSReadLine/Keys.cs (hunk 1 above)
Comment (daxian-dbw) [reply PSReadLine/Keys.cs:243]: I only see the OemXXX `ConsoleKey`s generated for the dead keys that I have inspected so far ... Yes, `OemClear` is not in that range. I didn't include it only because I didn't see it was generated by the dead keys I have inspected :) I will keep the check as is for now, and change it as needed when there are new dead-key issue reported.

**Comment by daxian-dbw** [comment]
Test run passed with French keyboard layout:

image
