### PR TITLE
Sync ReadKeyProc thread with pipeline thread

### LINKED ISSUE #3292: Readline crashes with ThrowForEmptyQueue
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.3
PowerShell: 2022.4.2
OS: Microsoft Windows 10.0.19044
BufferWidth: 241
BufferHeight: 18

Last 200 Keys:

 Backspace Ctrl+v Spacebar - m a t c h Spacebar Enter
 Ctrl+@ $ m a t c h e s Enter
 Ctrl+@ UpArrow Enter
 Ctrl+@ UpArrow UpArrow Home RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Escape Ctrl+v LeftArrow Ctrl+w $ M a t c h e s . v a l u e Enter
 Ctrl+@ UpArrow LeftArrow Backspace Ctrl+w [ Backspace Backspace [ 0 ] Enter
 Ctrl+@ UpArrow LeftArrow UpArrow UpArrow UpArrow UpArrow Home LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow End LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Enter
 Ctrl+@ UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete RightArrow RightArrow RightArrow RightArrow Delete End Enter
 Ctrl+@ UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 Ctrl+@ $ m a t c e h s Enter
 Ctrl+@ UpArrow Backspace Backspace Backspace h e s Enter
 Ctrl+@ UpArrow UpArrow UpArrow UpArrow Escape i p m o Spacebar - f o r Spacebar b u i Tab Enter
 Ctrl+@ g n o Backspace Backspace m o Spacebar p s r e a d l i

### Exception

System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

image

### Environment data

```console
PS Version: 7.2.2
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.3
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 241
BufferHeight: 18
```

### Steps to reproduce

I was editing this expression when the crash happened:
```powershell
"6.0.300-preview.22204.3 [asdfo]"| Select-String -Pattern '\d*.\d*.\d*(-\w*\.\d*.\d*.\d*)?' | ForEach-Object { [System.Management.Automation.Seman$_.matches.value ```

### Expected behavior

No crash

### Actual behavior

crash

### PR DESCRIPTION
**Pull request by SeeminglyScience**
# PR Summary

Fix #3292

The pipeline thread was returning before the `ReadKeyProc` thread had finished processing the dummy input. This was occurring somewhat frequently when `ReadLine` was invoked multiple times in a row, surfacing a race condition.

With these changes, the pipeline thread will wait for dummy input to be received, dequeue the key, and continue with normal cancellation logic.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/3294)

### CODE REVIEW

**Review by andyleejordan — COMMENTED** [review]
Super freaking interesting. Can we setup a call with @daxian-dbw and step through this? I think you've found the threads racing, but damn, this is interesting.

**Comment by SeeminglyScience** [comment]
> Can we setup a call with @daxian-dbw and step through this?

Yeah definitely ❤️

File: PSReadLine/ReadLine.cs [hunk 1]
```diff
@@ -292,10 +279,12 @@ internal static PSKeyInfo ReadKey()
                 throw new OperationCanceledException();
             }
 
-            if (handleId == CancellationRequested)
+            if (_singleton._cancelReadCancellationToken.IsCancellationRequested)
```
Comment (daxian-dbw) [inline PSReadLine/ReadLine.cs:276]: ~There is a race condition that we reach here due to a timeout from `WaitHandle.WaitAny`, but then this check returns `true`. In this case, `Deque()` may raise an `Queue empty` exception depending on whether `ReadKeyProc` thread has enqueue the key.~

Nope, the timeout case won't affect this. Please ignore this comment.

**Review by daxian-dbw — COMMENTED** [review]
@SeeminglyScience Good work narrowing down the cause!
~There may still be a race condition with this change.~ timeout case won't affect this change. Looking.

File: PSReadLine/ReadLine.cs [hunk 2]
```diff
@@ -292,10 +278,12 @@ internal static PSKeyInfo ReadKey()
...
             {
-                // ReadLine was cancelled. Save the current line to be restored next time ReadLine
-                // is called, clear the buffer and throw an exception so we can return an empty string.
+                // ReadLine was cancelled. Dequeue the dummy input sent by the host, save the current
+                // line to be restored next time ReadLine is called, clear the buffer and throw an
+                // exception so we can return an empty string.
+                _singleton._queuedKeys.Dequeue();
```
Comment (daxian-dbw) [inline PSReadLine/ReadLine.cs:281]: Please update the comment at the line `handleId = WaitHandle.WaitAny(_singleton._requestKeyWaitHandles, 300)` -- remove the "cancellation" related line.

**Review by daxian-dbw — APPROVED** [review]
LGTM with a minor comment.

**Comment by andyleejordan** [comment]
Also tested and verified, and this resolves the problem. We've (well, @SeeminglyScience really) narrowed down the "extra prompt" issue as well, and while related to what we've been debugging, the cause is separate (our `DisconnectHandler` is erroneously causing us to cancel the REPL, which then gets invoked again immediately).

**Review by andyleejordan — APPROVED** [review]

File: PSReadLine/ReadLine.cs (hunk 2 above)
Comment (SeeminglyScience) [reply PSReadLine/ReadLine.cs:281]: Good catch! Also removed a constant that is no longer referenced.

File: PSReadLine/ReadLine.cs [hunk 3]
```diff
@@ -877,7 +861,7 @@ private void DelayedOneTimeInitialize()
             _readKeyWaitHandle = new AutoResetEvent(false);
             _keyReadWaitHandle = new AutoResetEvent(false);
             _closingWaitHandle = new ManualResetEvent(false);
-            _requestKeyWaitHandles = new WaitHandle[] {_keyReadWaitHandle, _closingWaitHandle, null};
```
Comment (andyleejordan) [inline PSReadLine/ReadLine.cs:880]: Ah ha, the questions I had earlier but hadn't written yet are now irrelevant. Yay!

**Comment by daxian-dbw** [comment]
Would it make sense to use `CancellationToken.None` instead of the static `_defaultCancellationToken` now? I think the only place `_defaultCancellationToken` is used is in `public static string ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, bool? lastRunStatus)`.

**Comment by SeeminglyScience** [comment]
> Would it make sense to use `CancellationToken.None` instead of the static `_defaultCancellationToken` now? I think the only place `_defaultCancellationToken` is used is in `public static string ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, bool? lastRunStatus)`.

Oooo another good catch, yeah I think that would work fine now since `IsCancellationRequested` doesn't change when you do `CancellationToken.None.WaitHandle.Set()`. I'll get that changed

**Review by daxian-dbw — APPROVED** [review]
LGTM!

**Comment by andyleejordan** [comment]
Woo-hoo!
