### PR TITLE
Make PageUp/PageDown and CtrlPageUp/CtrlPageDown windows only

### LINKED ISSUE #1016: PageDown while pwsh is processing command => System.PlatformNotSupportedException
Pressing  PageDown while pwsh is processing command gives System.PlatformNotSupportedException
### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.3
OS: Linux 4.4.0-18898-Microsoft #1000-Microsoft Fri May 10 16:34:00 PST 2019
Last 17 Keys
```
 l l Enter
 l s Enter
 c d Spacebar I m Tab Enter
 l s Enter
 PageDown
```

### Exception
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

### PR DESCRIPTION
**Pull request by daxian-dbw**
Make PageUp/PageDown and CtrlPageUp/CtrlPageDown windows only because
1. On Linux and macOS, `Console.SetWindowPosition` throw `PlatformNotSupportedException`.
2. On macOS, <kbd>PageUp</kbd> and <kbd>PageDown</kbd> get intercepted by the terminal and perform the same behavior as moving one page up or down.
    <kbd>Ctrl+PageUp</kbd> and <kbd>Ctrl+PageDown</kbd> are also intercepted by the terminal and do the same as <kbd>PageUp</kbd> and <kbd>PageDown</kbd>

Fix #1016

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@msftrncs can you please review? Thanks!

File: PSReadLine/KeyBindings.cs [hunk 1]
```diff
@@ -229,24 +229,28 @@ void SetDefaultWindowsBindings()
...
-                { Keys.CtrlPageUp,             MakeKeyHandler(ScrollDisplayUpLine,       "ScrollDisplayUpLine") },
-                { Keys.CtrlPageDown,           MakeKeyHandler(ScrollDisplayDownLine,     "ScrollDisplayDownLine") },
                 // Added for xtermjs-based terminals that send different key combinations.
                 { Keys.AltD,                   MakeKeyHandler(KillWord,                  "KillWord") },
                 { Keys.CtrlAt,                 MakeKeyHandler(MenuComplete,              "MenuComplete") },
                 { Keys.CtrlW,                  MakeKeyHandler(BackwardKillWord,          "BackwardKillWord")},
             };
 
             // Some bindings are not available on certain platforms
+            // For example, PageUp/PageDown and CtrlPageUp/CtrlPageDown bindings are supported on Windows only because
```
Comment (rjmholt) [inline PSReadLine/KeyBindings.cs]: Rather than `for example` above (which I feel invites further entries to skip an explanation of why they are platform-specific), maybe it's preferable to put explanatory comments above entries (or whitespace-separated groups of entries)

**Review by rjmholt — APPROVED** [review]
LGTM based on your description of the initial problem. Left a comment about comments

File: PSReadLine/KeyBindings.cs (hunk 1 above)
Comment (daxian-dbw) [reply PSReadLine/KeyBindings.cs]: Agreed. Will put this comment above the entries.
