### PR TITLE
Fix the menu completion to better handle the backspace key

### LINKED ISSUE #3559: exception ArgumentOutOfRangeException with setup "Tab to MenuComplete" and "HistorySearchCursorMovesToEnd"
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

PSReadLine_bug

### Environment data

```console
PS Version: 7.3.2
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 202
BufferHeight: 60
```

### Steps to reproduce

1. run `Set-PSReadlineKeyHandler -Chord Tab -Function MenuComplete` to enable menu completion with tab key
2. run `Set-PSReadLineOption -HistorySearchCursorMovesToEnd` to move cursor to the end after history search
3. have folders `strong` and `stronghold` in current empty folder
4. type following keys:
`c d Spacebar s Tab h Tab Backspace h`

### Expected behavior

No exception.

### Actual behavior

The above exception happens.

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #3559

Fix the menu completion to better handle the backspace key.

Keep this a draft PR until after adding tests.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/3574)

### CODE REVIEW

File: PSReadLine/Completion.cs [hunk 1]
```diff
@@ -983,14 +983,25 @@ unAmbiguousText.Length > (userComplPos + userCompletionText.Length))
...
-                        userCompletionText = userCompletionText.Substring(0, userCompletionText.Length - 1);
+                            menu = newMenu;
+                        }
+                        // else {
+                        //     We should not pop the stack yet. The updated user completion text contains characters
+                        //     that are not included in the selected item of the menu at the top of stack. This may
+                        //     happen when the user pressed a 'Tab' before this 'Backspace', which updated the user
+                        //     completion text to include the unambiguous common prefix of the available completion
+                        //     candidates. In this case, we should stay in the current menu.
+                        // }
```
Comment (andyleejordan) [inline PSReadLine/Completion.cs:1004]: Ahh thank you super helpful comment 😄

**Review by andyleejordan — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@andschwa Thanks for the review!
